name: Test documentation

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/mgcd'
  ARTIFACT: 'webHelpMGCD2-all.zip'
  DOCKER_VERSION: '233.14938'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set ALGOLIA_KEY environment variable
        env:
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
        run: echo "ALGOLIA_KEY is $ALGOLIA_KEY"

      - name: Access ALGOLIA_KEY environment variable
        run: echo "ALGOLIA_KEY from env is ${{ env.ALGOLIA_KEY }}"

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}
